# Generated by Django 5.0.7 on 2024-08-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="status",
            field=models.CharField(
                choices=[("r", "Requested"), ("a", "Approved"), ("d", "Denied")],
                default="r",
                max_length=1,
            ),
        ),
    ]
