# Generated by Django 5.0.7 on 2024-08-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0002_alter_restaurant_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="is_soft_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
