# Generated by Django 5.0.7 on 2024-08-08 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="total",
            new_name="total_price",
        ),
    ]
