default_stages:
  - commit
repos:
  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
        args: # arguments to configure black
          - --line-length=120
          - --include='\.pyi?$'

          # these folders wont be formatted by black
          - --exclude="""\.git |
            \.__pycache__|
            \.hg|
            \.mypy_cache|
            \.tox|
            \.venv|
            _build|
            buck-out|
            build|
            dist"""
        language_version: python3.12
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
        - id: check-added-large-files
        - id: check-ast
        - id: check-merge-conflict
        - id: check-byte-order-marker
        - id: check-case-conflict
        - id: check-executables-have-shebangs
        - id: check-json
        - id: check-toml
        - id: debug-statements
        - id: detect-private-key
        - id: end-of-file-fixer
        - id: requirements-txt-fixer
        - id: trailing-whitespace
  -   repo: https://github.com/PyCQA/flake8
      rev: 5.0.4
      hooks:
        -   id: flake8
            args: # arguments to configure flake8
              - "--max-line-length=120"
              - "--max-complexity=18"
              - "--select=B,C,E,F,W,T4,B9"
              - "--ignore=E712,E231,E203,E266,E501,W503,F403,F401,E402,E701,W503,W291,E203,E126,W605,F405,C901,F821,E711"
  - repo: local
    hooks:
      - id: refurb
        stages:
          - pre-push
        name: refurb
        language: system
        types: [python]
        entry: refurb
