x-environment: &COMMON_VARS
  DJANGO_SETTINGS_MODULE: 'config.settings.local'
  ENVIRONMENT: 'LOCAL'

services:
  backend:
    extends:
      service: backend
      file: docker-compose.base.yaml
    env_file:
      - envs/.env.local
    environment:
      *COMMON_VARS
  celery:
    extends:
      service: celery
      file: docker-compose.base.yaml
    env_file:
      - envs/.env.local
    environment:
      *COMMON_VARS
  celery-beat:
    extends:
      service: celery-beat
      file: docker-compose.base.yaml
    env_file:
      - envs/.env.local
    environment:
      *COMMON_VARS
  postgres:
    extends:
      service: postgres
      file: docker-compose.base.yaml
    env_file:
      - envs/.env.local
  redis:
    extends:
      service: redis
      file: docker-compose.base.yaml
  smtp4dev:
    extends:
      service: smtp4dev
      file: docker-compose.base.yaml

networks:
  main:

volumes:
  food_anywhere_postgres_data:
