services:
  backend:
    restart: on-failure
    command: sh ./docker/scripts/backend.sh
    container_name: food-anywhere-backend
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/src
    networks:
      - main
    depends_on:
        postgres:
            condition: service_healthy
        redis:
            condition: service_healthy
  celery:
    restart: on-failure
    container_name: food-anywhere-celery
    command: sh ./docker/scripts/celery.sh
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/src
      - ./logs/celery.log:/var/log/celery.log
    networks:
      - main
    depends_on:
        backend:
            condition: service_started
  celery-beat:
    restart: on-failure
    container_name: food-anywhere-celery-beat
    command: sh ./docker/scripts/celery.sh
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/src
      - ./logs/celery.log:/var/log/celery-beat.log
    networks:
      - main
    depends_on:
      backend:
        condition: service_started
  postgres:
    restart: on-failure
    container_name: food-anywhere-postgres
    image: postgres:16.3-alpine
    expose:
      - "5432"
    volumes:
      - food_anywhere_postgres_data:/var/lib/postgresql/data/
    networks:
      - main
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5
  redis:
    restart: on-failure
    container_name: food-anywhere-redis
    image: redis:6.2-alpine
    expose:
      - "6379"
    networks:
      - main
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 2s
      timeout: 5s
      retries: 5
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    container_name: food-anywhere-smtp4dev
    ports:
      - "5000:80"
    expose:
      - "25"
    networks:
      - main
  promtail:
    image: grafana/promtail
    container_name: food-anywhere-promtail
    volumes:
      - ./promtail/config.yaml:/etc/promtail/promtail.yaml
      - ./logs/:/var/log/
    command: --config.file=/etc/promtail/promtail.yaml
    depends_on:
      - backend
    networks:
      - main
  loki:
    image: grafana/loki
    container_name: food-anywhere-loki
    ports:
      - "3100:3100"
    depends_on:
      - promtail
    networks:
      - main
  grafana:
    image: grafana/grafana
    container_name: food-anywhere-grafana
    ports:
      - 3000:3000
    depends_on:
      - loki
    networks:
      - main
    volumes:
      - food_anywhere_grafana_data:/var/lib/grafana


networks:
  main:
