x-environment: &COMMON_VARS
  DJANGO_SETTINGS_MODULE: 'config.settings.local'
  ENVIRONMENT: 'LOCAL'

services:
  backend:
    extends:
      service: backend
      file: docker-compose.base.yaml
    env_file:
      - envs/.env.local
    environment:
      *COMMON_VARS
  postgres:
    extends:
      service: postgres
      file: docker-compose.base.yaml
    env_file:
      - envs/.env.local

networks:
  main:

volumes:
  food_anywhere_postgres_data:
