services:
  backend:
    restart: on-failure
    command: sh ./docker/scripts/backend.sh
    container_name: food-anywhere-backend
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/src
    networks:
      - main

  postgres:
    restart: on-failure
    container_name: sample-postgres
    image: postgres:16.3-alpine
    expose:
      - "5432"
    volumes:
      - food_anywhere_postgres_data:/var/lib/postgresql/data/
    networks:
      - main
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5

networks:
  main:
