x-environment: &COMMON_VARS
  DJANGO_SETTINGS_MODULE: 'config.settings.prod'
  ENVIRONMENT: 'PRODUCTION'

services:
  backend:
    extends:
      service: backend
      file: docker-compose.base.yaml
    env_file:
      - envs/.env.local
    environment:
      *COMMON_VARS
  celery:
    extends:
      service: celery
      file: docker-compose.base.yaml
    env_file:
      - envs/.env.prod
    environment:
      *COMMON_VARS
  celery-beat:
    extends:
      service: celery-beat
      file: docker-compose.base.yaml
    env_file:
      - envs/.env.prod
    environment:
      *COMMON_VARS
  postgres:
    extends:
      service: postgres
      file: docker-compose.base.yaml
    env_file:
      - envs/.env.prod
  redis:
    extends:
      service: redis
      file: docker-compose.base.yaml
  promtail:
    extends:
      service: promtail
      file: docker-compose.base.yaml
  loki:
    extends:
      service: loki
      file: docker-compose.base.yaml
  grafana:
    extends:
      service: grafana
      file: docker-compose.base.yaml

networks:
  main:

volumes:
  food_anywhere_postgres_data:
  food_anywhere_grafana_data:
