apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    uid: prometheus-datasource
    access: browser
    url: http://prometheus:9090
    isDefault: false
    version: 1
    editable: true
    basicAuth: false

  - name: loki
    type: loki
    uid: my-loki
    access: server
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true

  - name: jaeger
    type: jaeger
    uid: my-jaeger
    access: browser
    url: http://jaeger:16686
    isDefault: false
    version: 1
    editable: true
    basicAuth: false
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: my-loki
        tags: []
        mappedTags: [{ key: 'food-anywhere-backend', value: 'app' }]
        mapTagNamesEnabled: true
