# Generated by Django 5.0.7 on 2024-08-03 15:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_location_description_alter_location_latitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("user", "longitude", "latitude")},
        ),
    ]
