# Generated by Django 5.0.7 on 2024-08-03 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0003_alter_location_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("user", "location")},
        ),
    ]
