# Generated by Django 5.0.7 on 2024-08-03 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0004_alter_location_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="location",
            unique_together=set(),
        ),
    ]
