# Generated by Django 5.0.7 on 2024-08-04 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0005_alter_location_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("user", "is_primary"),
                name="unique_primary_location",
            ),
        ),
    ]
