# Generated by Django 5.0.7 on 2024-08-04 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0006_location_is_primary_location_unique_primary_location"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="location",
            name="unique_primary_location",
        ),
    ]
