# Generated by Django 5.0.7 on 2024-08-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="is_added_to_balance",
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
    ]
