# Generated by Django 5.0.7 on 2024-08-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_remove_transaction_is_added_to_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("refund", "Refund"),
                ],
                max_length=20,
            ),
        ),
    ]
