# Generated by Django 5.0.7 on 2024-08-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("p", "Pending"),
                    ("s", "Success"),
                    ("f", "Failed"),
                    ("c", "Cancelled"),
                    ("e", "Expired"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("d", "Deposit"),
                    ("w", "Withdrawal"),
                    ("c", "Charge"),
                    ("o", "Cost"),
                ],
                max_length=20,
            ),
        ),
    ]
