name: "Test On Docker"
description: "Test The Code On Docker Platform"


runs:
  using: composite
  steps:
    - name: SetUp Docker
      uses: docker/setup-buildx-action@v2

    - name: Run Containers
      run: make run DETACHED=true
      shell: bash

    - name: Run tests
      run: make test
      shell: bash
