apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-anywhere-celery-dp
  labels:
    app: food-anywhere-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-anywhere-celery
  template:
    metadata:
      labels:
        app: food-anywhere-celery
    spec:
      containers:
        - name: celery-master
          image: ml06py/food_anywhere:latest
          command: ["/bin/sh"]
          args: [ "./docker/scripts/celery.sh" ]

          envFrom:
            - configMapRef:
                name: food-anywhere-env

          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "config.settings.local"
            - name: ENVIRONMENT
              value: "LOCAL"


        - name: celery-slave
          image: ml06py/food_anywhere:latest
          command: ["/bin/sh"]
          args: [ "./docker/scripts/celery-beat.sh" ]

          envFrom:
            - configMapRef:
                name: food-anywhere-env
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "config.settings.local"
            - name: ENVIRONMENT
              value: "LOCAL"
