apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-anywhere-loki-dp
  labels:
    app: food-anywhere-loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-anywhere-loki
  template:
    metadata:
      labels:
        app: food-anywhere-loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.5.0
          ports:
            - containerPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  selector:
    app: food-anywhere-loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
