apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-anywhere-node-exporter-dp
  labels:
    app: food-anywhere-node-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-anywhere-node-exporter
  template:
    metadata:
      labels:
        app: food-anywhere-node-exporter
    spec:
      containers:
        - name: node-exporter
          image: quay.io/prometheus/node-exporter:latest
          ports:
            - containerPort: 9100

---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
spec:
  selector:
    app: food-anywhere-node-exporter
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
