apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-anywhere-redis-dp
  labels:
    app: food-anywhere-redis

spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-anywhere-redis

  template:
    metadata:
      labels:
        app: food-anywhere-redis
    spec:
      containers:
        - name: redis
          image: redis:6.2-alpine
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: food-anywhere-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
