apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-anywhere-smtp-dp
  labels:
    app: food-anywhere-smtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-anywhere-smtp
  template:
    metadata:
      labels:
        app: food-anywhere-smtp
    spec:
      containers:
        - name: smtp
          image: rnwood/smtp4dev:v3
          ports:
            - name: tcp-80
              containerPort: 80
            - name: tcp-25
              containerPort: 25
---

apiVersion: v1
kind: Service
metadata:
  name: smtp4dev
spec:
  selector:
    app: food-anywhere-smtp
  ports:
    - name: http
      port: 5000
      targetPort: tcp-80
    - name: smtp
      port: 25
      targetPort: tcp-25
