name: Test On Kubernetes
description: "Test the application on kubernetes using k3s"

runs:
  using: 'composite'
  steps:
    - uses: debianmaster/actions-k3s@master
      id: k3s
      with:
        version: 'latest'

    - name: Create ConfigMap
      run: make local_confmap
      shell: bash

    - name: Run Kubernetes Deployments
      run: make k8s
      shell: bash

    - name: Wait for Postgres Service
      run: kubectl wait --for=condition=available --timeout=60s deployment/food-anywhere-postgres-dp
      shell: bash

    - name: Wait for Redis Service
      run: kubectl wait --for=condition=available --timeout=60s deployment/food-anywhere-redis-dp
      shell: bash

    - name: Wait for Smtp4dev Service
      run: kubectl wait --for=condition=available --timeout=60s deployment/food-anywhere-smtp4dev-dp
      shell: bash

    - name: Wait for Backend Deployments
      run: kubectl wait --for=condition=available --timeout=60s deployment/food-anywhere-backend-dp
      shell: bash

    - name: Run Backend Tests
      run: kubectl exec -it $(kubectl get pods | grep backend | awk '{print $1}') -- pytest
      shell: bash
