# Generated by Django 5.0.7 on 2024-08-02 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("a", "Android"),
                            ("i", "iOS"),
                            ("w", "Windows"),
                            ("m", "macOS"),
                            ("l", "Linux"),
                            ("u", "Unknown"),
                        ],
                        default="u",
                        max_length=1,
                    ),
                ),
                (
                    "browser_type",
                    models.CharField(
                        choices=[
                            ("c", "Chrome"),
                            ("f", "Firefox"),
                            ("s", "Safari"),
                            ("e", "Edge"),
                            ("o", "Opera"),
                            ("u", "Unknown"),
                        ],
                        default="u",
                        max_length=1,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Active Session",
                "verbose_name_plural": "Active Sessions",
                "ordering": ["-date"],
            },
        ),
    ]
