# Generated by Django 5.0.7 on 2024-08-02 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("active_sessions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activesession",
            name="is_deleted",
        ),
    ]
