name: Academy Master Tests

on:
  push:
    branches: [main]
  workflow_dispatch:


env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/food_anywhere

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Build Docker Image
          uses: ./.github/actions/build
          with:
            image_name: ${{ env.IMAGE_NAME }}
            registry: ${{ env.REGISTRY }}
            dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
            dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
